server:
  port: 8081

spring:
  application:
    name: course-service

  datasource:
    url: jdbc:postgresql://localhost:5432/courseDB
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ordukhanm20@gmail.com
    password: jgpjxzpmzosgznry
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000s
    cache:
      type: redis
      ttl-seconds: 60

application:
  config:
    student-url: http://localhost:8080/api
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 300000
      refresh-token:
        expiration: 604800000

logging:
  file:
    name: logs/course-service.log
  level:
      com:
        car:
          courseservice: INFO
      org:
        springframework:
          web: DEBUG